apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-management-grpc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.management.service.grpc.type }}
  ports:
    - port: {{ .Values.management.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "netbird.management.selectorLabels" . | nindent 4 }}
