apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.management.service.http.type }}
  ports:
    - port: {{ .Values.management.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "netbird.management.selectorLabels" . | nindent 4 }}
