apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  {{- if not .Values.management.autoscaling.enabled }}
  replicas: {{ .Values.management.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netbird.management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/management-cm.yaml") . | sha256sum }}
        {{- with .Values.management.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "netbird.management.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.management.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird.management.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.management.podSecurityContext | nindent 8 }}
      initContainers:
        - name: configure
          image: {{ .Values.management.initPod.image.repository }}:{{ .Values.management.initPod.image.tag }}
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              /bin/sh /tmp/netbird/kubeconfig-gen.sh &&
              vals get "$(cat /tmp/netbird/management.tmpl.json)" > /etc/netbird/management.json
          env:
          - name: KUBECONFIG
            value: /tmp/kubeconfig
          {{- range $key, $val := .Values.management.initPod.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.management.initPod.envRaw }}
            {{- with .Values.management.initPod.envRaw }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/netbird
              name: config
            - mountPath: /tmp/netbird
              name: config-template
      containers:
        - name: {{ .Chart.Name }}-management
          securityContext:
            {{- toYaml .Values.management.securityContext | nindent 12 }}
          image: "{{ .Values.management.image.repository }}:{{ .Values.management.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          {{- if hasKey .Values.management.podCommand "command" }}
          command:
          - {{ .Values.management.podCommand.command }}
          {{- end}}
          {{- if or (hasKey .Values.management.podCommand "args") (hasKey .Values.management.podCommand "xtraArgs")  }}
          args:
            {{- range .Values.management.podCommand.args }}
            - {{ . }}
            {{- end }}
            {{- range .Values.management.podCommand.xtraArgs }}
            - {{ . }}
            {{- end }}
          {{- end }}
          {{- if or (.Values.env) (.Values.envRaw) }}
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.envRaw }}
            {{- with .Values.envRaw }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.management.lifecycle }}
          lifecycle: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.management.service.http.containerPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.management.service.grpc.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.management.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/netbird
              name: config
            - mountPath: /var/lib/netbird
              name: management
          livenessProbe:
            tcpSocket:
              port: {{ .Values.management.service.grpc.containerPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.management.service.grpc.containerPort }}
      {{- with .Values.management.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.management.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.management.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          emptyDir:
            medium: Memory
        - name: config-template
          configMap:
            name: {{ include "netbird.fullname" . }}-management
        - name: management
          {{- if .Values.management.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "netbird.fullname" . }}-management
          {{- else }}
          emptyDir: {}
          {{- end }}
